name: PocketJobs
main: MinecrafterJPN\PocketJobs
author: MinecrafterJPN
version: 2.0
api: [3.11.0]
load: POSTWORLD
description: Introduces job into your world
website: https://github.com/MinecrafterJPN/PocketJobs
depend: [PocketMoney]
commands:
 jobs:
  desciption: PocketJobs main command
  usage: /jobs [subcommand]
  permission: pocketjobs.command
permissions:
 pocketjobs:
  default: true
  description: Allows using all the PocketJobs things
  children:
   pocketjobs.command:
    default: true
    description: Allows using all the PocketJobs commands
